---
title: "data_processing"
author: "Lukas Emge"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(ggplot2)
library(grid)
library(gridExtra)
library(rstanarm)
library(bayesplot)
```

```{r}
data_defense2017 <- read_csv("raw_data/2017Defense.csv", 
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

data_offense2017 <- read_csv("raw_data/2017Offense.csv",
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

# I loaded in the data from 2017 for offensive players and defensive players.

data2017 <- full_join(data_defense2017, data_offense2017, 
                      by = c("rk", "year", "player","pos", "av", "school", 
                             "college", "height", "wt", "x40yd", "vertical", 
                             "bench_reps", "broad_jump", "x3cone", "shuttle", 
                             "drafted_tm_rnd_yr"))

# I combined the 2017 offensive and defensive datasets into one 2017 dataset

data_defense2016 <- read_csv("raw_data/2016Defense.csv", 
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

data_offense2016 <- read_csv("raw_data/2016Offense.csv",
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

data2016 <- full_join(data_defense2016, data_offense2016, 
                      by = c("rk", "year", "player","pos", "av", "school", 
                             "college", "height", "wt", "x40yd", "vertical", 
                             "bench_reps", "broad_jump", "x3cone", "shuttle", 
                             "drafted_tm_rnd_yr"))

data_defense2015 <- read_csv("raw_data/2015Defense.csv", 
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

data_offense2015 <- read_csv("raw_data/2015Offense.csv",
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

data2015 <- full_join(data_defense2015, data_offense2015, 
                      by = c("rk", "year", "player","pos", "av", "school", 
                             "college", "height", "wt", "x40yd", "vertical", 
                             "bench_reps", "broad_jump", "x3cone", "shuttle", 
                             "drafted_tm_rnd_yr"))

data_defense2014 <- read_csv("raw_data/2014Defense.csv", 
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

data_offense2014 <- read_csv("raw_data/2014Offense.csv",
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

data2014 <- full_join(data_defense2014, data_offense2014, 
                      by = c("rk", "year", "player","pos", "av", "school", 
                             "college", "height", "wt", "x40yd", "vertical", 
                             "bench_reps", "broad_jump", "x3cone", "shuttle", 
                             "drafted_tm_rnd_yr"))

data_defense2013 <- read_csv("raw_data/2013Defense.csv", 
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

data_offense2013 <- read_csv("raw_data/2013Offense.csv",
                         col_types = cols(
  Rk = col_double(),
  Year = col_double(),
  Player = col_character(),
  Pos = col_character(),
  AV = col_double(),
  School = col_character(),
  College = col_character(),
  Height = col_character(),
  Wt = col_double(),
  `40YD` = col_double(),
  Vertical = col_double(),
  BenchReps = col_double(),
  `Broad Jump` = col_double(),
  `3Cone` = col_double(),
  Shuttle = col_double(),
  `Drafted (tm/rnd/yr)` = col_character()
)) %>% 
  clean_names()

data2013 <- full_join(data_defense2013, data_offense2013, 
                      by = c("rk", "year", "player","pos", "av", "school", 
                             "college", "height", "wt", "x40yd", "vertical", 
                             "bench_reps", "broad_jump", "x3cone", "shuttle", 
                             "drafted_tm_rnd_yr"))

# Above, I continued the process of reading in the different year's offensive
# and defensive datasets followed by combining them into one yearly dataset.

data2017_2016 <- full_join(data2017, data2016, 
                      by = c("rk", "year", "player","pos", "av", "school", 
                             "college", "height", "wt", "x40yd", "vertical", 
                             "bench_reps", "broad_jump", "x3cone", "shuttle", 
                             "drafted_tm_rnd_yr"))

data2017_2016_2015 <- full_join(data2017_2016, data2015, 
                      by = c("rk", "year", "player","pos", "av", "school", 
                             "college", "height", "wt", "x40yd", "vertical", 
                             "bench_reps", "broad_jump", "x3cone", "shuttle", 
                             "drafted_tm_rnd_yr"))

data2017_2016_2015_2014 <- full_join(data2017_2016_2015, data2014, 
                      by = c("rk", "year", "player","pos", "av", "school", 
                             "college", "height", "wt", "x40yd", "vertical", 
                             "bench_reps", "broad_jump", "x3cone", "shuttle", 
                             "drafted_tm_rnd_yr"))

combine_data <- full_join(data2017_2016_2015_2014, data2013, 
                      by = c("rk", "year", "player","pos", "av", "school", 
                             "college", "height", "wt", "x40yd", "vertical", 
                             "bench_reps", "broad_jump", "x3cone", "shuttle", 
                             "drafted_tm_rnd_yr"))

# Abovem I combined all of the years datasets.

combine_data <- combine_data %>% 
  separate(drafted_tm_rnd_yr,
c("team", "round", "pick_number"), " / ") 

combine_data <- combine_data %>% 
  separate(pick_number, c("pick_#", "extra"), "th pick")

combine_data <- combine_data %>% 
  separate(`pick_#`, c("pick", "extra_1"), "st pick")

combine_data <- combine_data %>% 
  separate(pick, c("pick", "extra_2"), "nd pick")

combine_data <- combine_data %>% 
  separate(pick, c("pick", "extra_3"), "rd pick")

combine_data <- combine_data %>% 
  select(-"extra") %>% 
  select(-"extra_1") %>% 
  select(-"extra_2") %>% 
  select(-"extra_3")
  

combine_data$pick <- as.numeric(as.character(combine_data$pick))

# A huge problem I had was the fact that there was not a column that contained the
# draft position as a number, but instead there was a column that contained the round
# followed by the team followed by the draft position. I used a series of seperates to 
# eventually create three seperate columns called team, round, and pick. I then changed
# the pick column to numeric. This was SUPER important because I couldnt analyze any of the
# tests affect on draft position unless I had a number value for draft position.

combine_data <- combine_data %>% 
  drop_na(pick)

write_rds(combine_data, "Athlete-Injuries/combine_data.rds")

combine_data %>% 
  pivot_longer(cols = c(x40yd, vertical, bench_reps, broad_jump, x3cone, shuttle), 
               names_to = "test", values_to = "result") %>% 
  group_by(test) %>% 
  summarise(average = mean(result, na.rm = TRUE), .groups = "drop")

# Testing to make sure I could find the mean of different tests


   combine_data %>% 
        pivot_longer(cols = c(x40yd, vertical, bench_reps, broad_jump, x3cone, shuttle), 
                     names_to = "test", values_to = "result") %>% 
        group_by(test) %>% 
        summarise(nfl_average = mean(result, na.rm = TRUE), .groups = "drop") %>% 
        filter(test == "x40yd") -> nfl_average
   
   # Testing how to find the NFL Average of a specific test. This was used in the
   # 3rd tab - Team by Team.
      
      
      combine_data %>% 
        select(x40yd, vertical, bench_reps, broad_jump, x3cone, shuttle, team, pos) %>% 
        filter(team == "Pittsburgh Steelers",
               pos == "CB") %>% 
        pivot_longer(cols = c(x40yd, vertical, bench_reps, broad_jump, x3cone, shuttle), 
                     names_to = "test", values_to = "result") %>% 
        group_by(test) %>% 
        summarise(average = mean(result, na.rm = TRUE), .groups = "drop") %>% 
        filter(test == "x40yd") %>% 
        full_join(nfl_average)
      
      # Testing how to find the average of a specific event for a specific team. I then
      # joined this with the nfl_average from above to check how that worked.
      
   combine_data %>% 
        filter(pos %in% "DT") %>% 
        drop_na(x40yd) %>% 
        drop_na(broad_jump) -> testingdata
         
         
cor(testingdata$x40yd, testingdata$broad_jump, method = "spearman")

# This was testing how to find the correlation for the first graph so that I
# could print it somewhere on the graph.
      
  
        
      
     # combine_data %>% 
      #  filter(pos %in% "DT") %>% 
       #     ggplot(aes(x = x40yd, y = broad_jump)) + 
        #    geom_point() + 
        #geom_smooth(method = "lm", se = FALSE) %>% 
        #annotation_custom(grob1)
              
         # I commented the above out, but this further shows the struggle
# of me trying to find how to print the correlation in the first graph.
      
      
    fit_40 <-  stan_glm(data = combine_data,
               formula = pick ~ x40yd -1,
               family = gaussian(),
               refresh = 0)
    
    print(fit_40)
    
    # Running the model on just 40 yard dash to see the effect.
    
    posterior_interval(fit_40)
    
    posterior <- as.array(fit_40)
    dim(posterior)
    dimnames(posterior)
    color_scheme_set("red")
    mcmc_areas(posterior, par= "x40yd")
    
   newdata <- combine_data %>% 
      select(pick, x40yd) %>% 
      drop_na(x40yd) %>% 
      head(1)
      
  posterior_predict(fit_40, newdata = newdata) %>% 
    as_tibble() %>% 
    ggplot(aes(x = `1`)) + 
    geom_histogram()
  
  # I originally tried to conceptualize the stan_glm by graphing the 
  # posterior predictions. However, this graph did not give much information 
  # so I scrapped it.
        
  
  fit <- stan_glm(data = combine_data,
                        formula = pick ~ x40yd + vertical + bench_reps + broad_jump + x3cone + shuttle - 1,
                        family = gaussian(),
                        refresh = 0)
  
  stan_glm(data = combine_data,
                        formula = pick ~ x40yd - 1,
                        family = gaussian(),
                        refresh = 0)
  
  stan_glm(data = combine_data,
                        formula = pick ~ vertical - 1,
                        family = gaussian(),
                        refresh = 0)
  
  stan_glm(data = combine_data,
                        formula = pick ~ bench_reps - 1,
                        family = gaussian(),
                        refresh = 0)
  
  stan_glm(data = combine_data,
                        formula = pick ~ broad_jump - 1,
                        family = gaussian(),
                        refresh = 0)
  
  
  stan_glm(data = combine_data,
                        formula = pick ~ x3cone - 1,
                        family = gaussian(),
                        refresh = 0)
  
  stan_glm(data = combine_data,
                        formula = pick ~ shuttle - 1,
                        family = gaussian(),
                        refresh = 0)
  
 # Running all the different models. 




       
```

